### ISSUE TITLE
Error message for entering less than 4 characters for username  under update user profile.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#603]
When we enter username less than 4 character, the error message should be listed under Responses.

**To Reproduce**

1. Go to 'user-update user profile'
2. provide authorization access token
3. {
  "name": "123”,
  "username": "123",
  "bio": "string",
  "occupation": "string",
  "organization": "string",
  "slack_username": "string",
  "social_media_links": "string",
  "skills": "string",
  "interests": "string",
  "resume_url": "string",
  "photo_url": "string",
  "need_mentoring": false,
  "available_to_mentor": false,
  "location": "string"
}

4.  Click on 'Execute'
5. Scroll down to 'Responses'
6. 
![Screenshot (81)](https://user-images.githubusercontent.com/50888936/82258603-c0060780-9977-11ea-937a-3ed3503413cd.png)

**Expected behavior**
That error message should be listed in the responses.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser  chrome

**Comment by Bhavani-Somanchi** [comment]
@faznan3nazer  Can I work on this issue?

**Comment by ashokrayal** [comment]
Hi @faznan3nazer ,
Can you assigned this to me? I have no current issue in progress. 
Thanks

**Comment by priyanshuone6** [comment]
Hey, can you please assign this issue to me

**Comment by priyanshuone6** [comment]
Hey can you please assign this issue to me

**Comment by vj-codes** [comment]
Assigning you @priyanshuone6 
Happy coding!

**Comment by devkapilbansal** [comment]
@vj-codes @isabelcosta  this issue is already resolved in #959 when testing and fixing APIs as per this comment https://github.com/anitab-org/mentorship-backend/pull/959#issuecomment-756008533. Kindly close this issue and linked pull request.

**Comment by vj-codes** [comment]
@devkapilbansal I still don't see a response under 400 responses in update user profile,can you please elaborate ?
#959 is for register endpoint , this is for update user endpoint.

**Comment by devkapilbansal** [comment]
Closing this as it was a duplicate of #574 

CC: @isabelcosta

**Comment by devkapilbansal** [comment]
> @devkapilbansal I still don't see a response under 400 responses in update user profile,can you please elaborate ?
> #959 is for register endpoint , this is for update user endpoint.

@vj-codes it was solve in another issue but I mentioned #959 because there the message was corrected by @NenadPantelic stating `USERNAME_HAS_INVALID_LENGTH` rather than `USERNAME_FIELD_IS_EMPTY`

**Comment by devkapilbansal** [comment]
@vj-codes here is the line
https://github.com/anitab-org/mentorship-backend/blob/f3c23604767e8952bc2a66579366310607883a4c/app/api/resources/user.py#L307

https://github.com/anitab-org/mentorship-backend/blob/f3c23604767e8952bc2a66579366310607883a4c/app/messages.py#L57-L59

**Comment by vj-codes** [comment]
@devkapilbansal thank you got it:)
